### ISSUE TITLE
PreProc .split(',') does not successfully split entries with commas

### ISSUE THREAD

**Issue by patrickstocklin** [patrickstocklin/campus-crime#4]
Whenever an address contains a comma, it messes up how many fields we store in PreProc.py

**Comment by DCtheTall** [comment]
There is some hope!

over 95% of the entries (I have checked this myself) are exactly the same if you parse the first couple elements (univ name, state, city) and then all of the numbers are identically formatted _from the end of the line_. This allowed me to collect the data. Now, there is an issue with the KeyErrors which prevent me from writing the dictionaries to one giant DataFrame.
